import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta, timezone

from db.connection import SessionLocal
from db.news_item import NewsItem


def get_latest_news(hours: int = 24) -> list[NewsItem]:
    """Fetch latest news items from the database."""
    db = SessionLocal()
    try:
        cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
        news_items = db.query(NewsItem).filter(
            NewsItem.published_at >= cutoff
        ).order_by(NewsItem.published_at.desc()).all()
        return news_items
    finally:
        db.close()


def format_email_body(news_items: list[NewsItem]) -> str:
    """Format news items into plain text email body."""
    # Group by source
    youtube_items = [n for n in news_items if n.source == "youtube"]
    openai_items = [n for n in news_items if n.source == "openai"]
    anthropic_items = [n for n in news_items if n.source == "anthropic"]

    date_str = datetime.now().strftime("%B %d, %Y")

    text = f"""
AI NEWS DIGEST - {date_str}
{'=' * 50}

Your daily roundup of AI news from OpenAI, Anthropic, and YouTube

"""

    # YouTube Section
    text += "📺 YOUTUBE VIDEOS\n"
    text += "-" * 30 + "\n"
    if youtube_items:
        for item in youtube_items:
            text += _format_news_item_text(item)
    else:
        text += "No YouTube videos in the last 24 hours\n"
    text += "\n"

    # OpenAI Section
    text += "🔵 OPENAI NEWS\n"
    text += "-" * 30 + "\n"
    if openai_items:
        for item in openai_items:
            text += _format_news_item_text(item)
    else:
        text += "No OpenAI news in the last 24 hours\n"
    text += "\n"

    # Anthropic Section
    text += "🟣 ANTHROPIC NEWS\n"
    text += "-" * 30 + "\n"
    if anthropic_items:
        for item in anthropic_items:
            text += _format_news_item_text(item)
    else:
        text += "No Anthropic news in the last 24 hours\n"
    text += "\n"

    text += f"""
{'=' * 50}
This email was automatically generated by your AI News Aggregator
"""

    return text


def _format_news_item_text(item: NewsItem) -> str:
    """Format a single news item as plain text."""
    published = item.published_at.strftime("%B %d, %Y at %I:%M %p") if item.published_at else "Unknown date"

    text = f"""
    * {item.title}
    Link: {item.url}
    Source: {item.source.capitalize()} | Published: {published}
    """

    if item.summary:
        text += f"""
        Summary: {item.summary}
        """

    return text  

def send_email(sender_email: str,sender_password: str,recipient_email: str,subject: str,text_body: str) -> bool:
    """Send email via Gmail SMTP."""
    import os
    print("ENV EMAIL:", os.getenv("GMAIL_SENDER_EMAIL"))
    print("ENV PASS:", os.getenv("GMAIL_APP_PASSWORD"))
    try:
        # Create message
        msg = MIMEMultipart()
        msg["Subject"] = subject
        msg["From"] = sender_email
        msg["To"] = recipient_email

        # Attach plain text body
        msg.attach(MIMEText(text_body, "plain"))

        # Connect to Gmail SMTP
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=10) as server:
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, recipient_email, msg.as_string())

        return True

    except Exception as e:
        print(f"Error sending email: {e}")
        return False


def send_daily_digest(sender_email: str,sender_password: str,recipient_email: str,hours: int = 24) -> dict:
    """
    Main function to send daily AI news digest.

    Args:
        sender_email: Gmail address to send from
        sender_password: Gmail app password
        recipient_email: Email address to receive the digest
        hours: Fetch news from last N hours (default: 24)

    Returns:
        dict with 'success' (bool) and 'message' (str)
    """

    print(f"📧 Fetching latest AI news from the last {hours} hours...")
    news_items = get_latest_news(hours=hours)

    if not news_items:
        print("No new news items found in the specified time range.")
        return {
            "success": True,
            "message": "No news items to send"
        }

    print(f"✅ Found {len(news_items)} news items")

    # Format email
    subject = f"🤖 AI News Digest - {datetime.now().strftime('%B %d, %Y')}"
    text_body = format_email_body(news_items)

    # Send email
    print("📤 Sending email...")
    success = send_email(
        sender_email=sender_email,
        sender_password=sender_password,
        recipient_email=recipient_email,
        subject=subject,
        text_body=text_body
    )

    if success:
        print("✅ Email sent successfully!")
        return {
            "success": True,
            "message": f"Sent {len(news_items)} news items to {recipient_email}"
        }
    else:
        print("❌ Failed to send email")
        return {
            "success": False,
            "message": "Failed to send email. Check your credentials."
        }

