name: AI News Daily

on:
  schedule:
    - cron: "30 18 * * *"   # 12:00 AM IST
  workflow_dispatch:        # allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run script
        run: uv run python main.py all --hours 24

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: 5432
      GMAIL_SENDER_EMAIL: ${{ secrets.GMAIL_SENDER_EMAIL }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}